# Generated by Django 3.1.2 on 2020-10-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of product')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image of product')),
                ('description', models.TextField(null=True, verbose_name='Product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Type of display')),
                ('resolution', models.CharField(max_length=255, verbose_name='Display resolution')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Accumulator volume')),
                ('ram', models.CharField(max_length=255, verbose_name='Random memory qty.')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=255, verbose_name='Max memory size')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Main camera resolution')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Frontal camera resolution')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of product')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image of product')),
                ('description', models.TextField(null=True, verbose_name='Product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('dispaly_type', models.CharField(max_length=255, verbose_name='Display type')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Processor frequenci')),
                ('ram', models.CharField(max_length=255, verbose_name='Random memory qty.')),
                ('video', models.CharField(max_length=255, verbose_name='Video card type')),
                ('time_withot_charge', models.CharField(max_length=255, verbose_name='Time to charge')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
